#!/bin/bash

# Ensure that the required ports are open
# Binder should automatically handle port forwarding for Bokeh server ports, but we'll ensure it's configured correctly


# Print out environment info for debugging
echo "JupyterHub IP: $JUPYTERHUB_SERVICE_PREFIX"
echo "Binder URL: $BINDER_URL"


